from Qt5CustomWidgets import ToggleButtonAnimated
from Qt5CustomWidgets import ProgressBar
from Qt5CustomWidgets import GraphicWidget
from Qt5CustomWidgets import QtHandlers, PlainTextEditHandler, DialogLogger