# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(637, 424)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ToggleButtonAnimated = ToggleButtonAnimated(Form)
        self.ToggleButtonAnimated.setMinimumSize(QtCore.QSize(70, 0))
        self.ToggleButtonAnimated.setToolTip("")
        self.ToggleButtonAnimated.setWhatsThis("")
        self.ToggleButtonAnimated.setChecked(True)
        self.ToggleButtonAnimated.setObjectName("ToggleButtonAnimated")
        self.horizontalLayout.addWidget(self.ToggleButtonAnimated)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ToggleButtonAnimated_2 = ToggleButtonAnimated(Form)
        self.ToggleButtonAnimated_2.setMinimumSize(QtCore.QSize(70, 0))
        self.ToggleButtonAnimated_2.setToolTip("")
        self.ToggleButtonAnimated_2.setWhatsThis("")
        self.ToggleButtonAnimated_2.setObjectName("ToggleButtonAnimated_2")
        self.horizontalLayout_2.addWidget(self.ToggleButtonAnimated_2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalSlider = QtWidgets.QSlider(Form)
        self.verticalSlider.setMaximum(200)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_3.addWidget(self.verticalSlider)
        self.ProgressBar = ProgressBar(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProgressBar.sizePolicy().hasHeightForWidth())
        self.ProgressBar.setSizePolicy(sizePolicy)
        self.ProgressBar.setMinimumSize(QtCore.QSize(100, 100))
        self.ProgressBar.setToolTip("")
        self.ProgressBar.setWhatsThis("")
        self.ProgressBar.setProperty("maximum", 200)
        self.ProgressBar.setProperty("penColor", QtGui.QColor(33, 37, 41, 0))
        self.ProgressBar.setProperty("barColor", QtGui.QColor(107, 107, 107))
        self.ProgressBar.setProperty("loadedColor", QtGui.QColor(211, 38, 54))
        self.ProgressBar.setProperty("textColor", QtGui.QColor(231, 231, 231))
        self.ProgressBar.setProperty("borderWidth", 1)
        self.ProgressBar.setProperty("roundingCorner", 10.0)
        self.ProgressBar.setProperty("showValue", False)
        self.ProgressBar.setObjectName("ProgressBar")
        self.horizontalLayout_3.addWidget(self.ProgressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButtonAdd = QtWidgets.QPushButton(Form)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.verticalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtWidgets.QPushButton(Form)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.verticalLayout.addWidget(self.pushButtonRemove)
        self.label.setBuddy(self.ToggleButtonAnimated)
        self.label_2.setBuddy(self.ToggleButtonAnimated_2)

        self.retranslateUi(Form)
        self.verticalSlider.valueChanged['int'].connect(self.ProgressBar.setValue)
        self.ToggleButtonAnimated.toggled['bool'].connect(self.ProgressBar.setShowPercent)
        self.ToggleButtonAnimated_2.toggled['bool'].connect(self.ProgressBar.setShowValue)
        self.ProgressBar.valueChanged['int'].connect(self.verticalSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.ToggleButtonAnimated, self.ToggleButtonAnimated_2)
        Form.setTabOrder(self.ToggleButtonAnimated_2, self.verticalSlider)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "show percent"))
        self.label_2.setText(_translate("Form", "show value"))
        self.pushButtonAdd.setText(_translate("Form", "Add 5"))
        self.pushButtonRemove.setText(_translate("Form", "Remove 5"))
from QtCustomWidgets.buttons.toggleButtonAnimated import ToggleButtonAnimated
from QtCustomWidgets.customProgressBar.progressBar import ProgressBar
