# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphicWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphicWidget(object):
    def setupUi(self, GraphicWidget):
        GraphicWidget.setObjectName("GraphicWidget")
        GraphicWidget.resize(653, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GraphicWidget.sizePolicy().hasHeightForWidth())
        GraphicWidget.setSizePolicy(sizePolicy)
        GraphicWidget.setMinimumSize(QtCore.QSize(0, 41))
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphicWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton = QtWidgets.QToolButton(GraphicWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(25, 25))
        self.toolButton.setMaximumSize(QtCore.QSize(25, 25))
        self.toolButton.setIconSize(QtCore.QSize(16, 16))
        self.toolButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setArrowType(QtCore.Qt.DownArrow)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.label = QtWidgets.QLabel(GraphicWidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.graphicsView = QChartView(GraphicWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(GraphicWidget)
        QtCore.QMetaObject.connectSlotsByName(GraphicWidget)

    def retranslateUi(self, GraphicWidget):
        _translate = QtCore.QCoreApplication.translate
        GraphicWidget.setWindowTitle(_translate("GraphicWidget", "GraphicWidget"))
        self.toolButton.setText(_translate("GraphicWidget", "..."))
        self.label.setText(_translate("GraphicWidget", "Graphic title"))


from PyQt5.QtChart import QChartView


